name: Call action


on:
  pull_request:
    branches:
      - main
      
  workflow_dispatch:
  
jobs:
  call-workflow:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repository
       uses: actions/checkout@v3
     - name: Action
       uses:  preethikrishnam/LearningRepo/Action@main
       
      
       
        
      

    
